FROM nvcr.io/nvidia/pytorch:23.06-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -y git vim libgtk2.0-dev && rm -rf /var/cache/apk/*

pip --no-cache-dir install Cython

COPY requirements.txt /workspace

RUN pip --no-cache-dir install -r /workspace/requirements.txt
RUN apt install default-jre
RUN apt install gnome-software

RUN apt-get update
RUN apt-get install python3-tk
RUN pip install fiftyone
RUN pip install 'huggingface_hub[cli,torch]'
RUN pip install transformers